  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - com.louishoughton::travel-map-api
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    TravelMapApiNativeFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided
        CodeUri: target/function.zip
        MemorySize: 128
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
            COGNITO_USER_POOL_ID: !Ref CognitoUserPool
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /{proxy+}
              Method: any
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        MfaConfiguration: "OFF"
        UserPoolName: travel-map-user-pool
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: True
            RequireSymbols: False
            RequireUppercase: True
    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: travel-map-web-client
        GenerateSecret: False
        UserPoolId:
          Ref: CognitoUserPool
    IdentityPool:
      Type: "AWS::Cognito::IdentityPool"
      Properties:
        IdentityPoolName: travel-map-identity-pool
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
          - ClientId: !Ref CognitoUserPoolClient
            ProviderName: !GetAtt CognitoUserPool.ProviderName
  Outputs:
    TravelMapApiNativeApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
      Export:
        Name: TravelMapApiNativeApi
