name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-      
    - name: Use Graal
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '20.0.0.java11'
    - run: java -version
    - run: mvn -v
    - run: mvn clean verify
      AWS_REGION: 'eu-west-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: mvn clean package -Dnative -Dquarkus.native.container-build=true -DskipTests
    - uses: louisblack/cloudformation-deploy-action@master
      env:
        TEMPLATE: './sam.native.yaml'
        AWS_STACK_NAME: travel-map-test
        AWS_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.S3_BUCKET }}
