name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Graal
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.0.java8'
    - run: java -version
    - run: mvn -v
    - run: mvn clean install -Dnative -Dquarkus.native.container-build=true
    - uses: actions/upload-artifact@master
      with:
        name: zip
        path: target/function.zip
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: zip
          path: target/function.zip
      - uses: louisblack/cloudformation-deploy-action@master
        env:
          TEMPLATE: './sam.native.yaml'
          AWS_STACK_NAME: travel-map-test
          AWS_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.S3_BUCKET }}
